[package]
name = "boxes-rs"
version = "0.1.0"
authors = ["Ritiek Malhotra <ritiekmalhotra123@gmail.com>"]
edition = "2018"

[dependencies]
rustbox = "0.11"
bincode = "1.1"
serde_derive = "1.0"
serde = "1.0"
